# *** apply-settings.ps1 ***
# *** Reads settings.json and writes the agent-tts config.js so the daemon picks up changes ***
# *** Run after every edit to settings.json ***

$ErrorActionPreference = 'Stop'

$root = Split-Path $PSScriptRoot -Parent
$settingsPath = Join-Path $root 'settings.json'
$agentTtsConfigDir = Join-Path $env:USERPROFILE '.config\agent-tts'
$agentTtsConfigPath = Join-Path $agentTtsConfigDir 'config.js'

if (-not (Test-Path $settingsPath)) {
    Write-Error "settings.json not found at $settingsPath"
    exit 1
}

$s = Get-Content $settingsPath -Raw | ConvertFrom-Json
if (-not (Test-Path $agentTtsConfigDir)) { New-Item -ItemType Directory -Path $agentTtsConfigDir | Out-Null }

# *** Build profiles array — one profile per skill so each gets its own voice ***
$profileBlocks = @()
foreach ($skillName in $s.skills.PSObject.Properties.Name) {
    $skill = $s.skills.$skillName
    $voice = if ($skill.voice) { $skill.voice } else { $s.agentTts.fallbackVoice }
    $speed = if ($skill.speed) { $skill.speed } else { $s.global.speed }
    $vol = if ($skill.volumeMultiplier) { $skill.volumeMultiplier } else { $s.global.volumeMultiplier }
    $profileBlocks += @"
    {
      id: 'skill-$skillName',
      name: '$skillName',
      description: 'Auto-generated profile for $skillName skill',
      enabled: true,
      parser: { type: '$($s.agentTts.parserType)', name: '$skillName' },
      watchPaths: [home + '\\.claude\\projects\\**\\*.jsonl'],
      ttsService: {
        type: 'kokoro',
        baseUrl: '$($s.global.kokoroBaseUrl)',
        voiceId: '$voice',
        voiceName: '$skillName ($voice)',
        options: {
          speed: $speed,
          responseFormat: '$($s.global.responseFormat)',
          volume_multiplier: $vol
        }
      }
    }
"@
}

# *** Per-mindset profiles — one profile per Brain mindset (ChatGPT / Claude / Gemini) ***
if ($s.PSObject.Properties.Name -contains 'mindsets') {
    foreach ($mindsetName in $s.mindsets.PSObject.Properties.Name) {
        if ($mindsetName.StartsWith('_')) { continue }
        $mindset = $s.mindsets.$mindsetName
        $voice = if ($mindset.voice) { $mindset.voice } else { $s.agentTts.fallbackVoice }
        $speed = if ($mindset.speed) { $mindset.speed } else { $s.global.speed }
        $vol = if ($mindset.volumeMultiplier) { $mindset.volumeMultiplier } else { $s.global.volumeMultiplier }
        $safeId = ($mindsetName -replace '[^A-Za-z0-9]', '-').ToLower()
        $profileBlocks += @"
    {
      id: 'mindset-$safeId',
      name: '$mindsetName',
      description: 'Auto-generated profile for Brain mindset $mindsetName',
      enabled: true,
      parser: { type: '$($s.agentTts.parserType)', name: '$mindsetName' },
      watchPaths: [home + '\\.claude\\projects\\**\\*.jsonl'],
      ttsService: {
        type: 'kokoro',
        baseUrl: '$($s.global.kokoroBaseUrl)',
        voiceId: '$voice',
        voiceName: '$mindsetName ($voice)',
        options: {
          speed: $speed,
          responseFormat: '$($s.global.responseFormat)',
          volume_multiplier: $vol
        }
      }
    }
"@
    }
}

# *** Default fallback profile (active when no skill-specific match) ***
$fallbackProfile = @"
    {
      id: 'claude-code-default',
      name: 'claude-code-default',
      description: 'Default profile for any Claude Code response not matching a skill',
      enabled: true,
      parser: { type: '$($s.agentTts.parserType)', name: 'Claude Code' },
      watchPaths: [home + '\\.claude\\projects\\**\\*.jsonl'],
      ttsService: {
        type: 'kokoro',
        baseUrl: '$($s.global.kokoroBaseUrl)',
        voiceId: '$($s.agentTts.fallbackVoice)',
        voiceName: 'Default ($($s.agentTts.fallbackVoice))',
        options: {
          speed: $($s.global.speed),
          responseFormat: '$($s.global.responseFormat)',
          volume_multiplier: $($s.global.volumeMultiplier)
        }
      }
    }
"@

$profilesJoined = ($profileBlocks + $fallbackProfile) -join ",`n"

$content = @"
/*** AUTO-GENERATED by scripts/apply-settings.ps1 — DO NOT EDIT BY HAND ***/
/*** Edit brain-skills/settings/sound/settings.json then re-run apply-settings.ps1 ***/

const home = process.env.USERPROFILE || process.env.HOME;

module.exports = {
  profiles: [
$profilesJoined
  ]
};
"@

$content | Out-File -FilePath $agentTtsConfigPath -Encoding utf8
Write-Host ('Wrote {0}' -f $agentTtsConfigPath)
Write-Host 'Restart agent-tts to apply: stop the running daemon then re-run agent-tts'